name: Build Android
on:
  workflow_call:

jobs:
  build-android:
    runs-on: self-hosted
    timeout-minutes: 20
    environment: ${{ github.event.inputs.environment || 'prod' }}
    env:
      DEPLOY_ENV: ${{ github.event.inputs.environment || 'prod' }}

    steps:
    - name: Download build files
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.build_files_name }}

    # Generate all the files needed for Android code signing
    - name: Setup Android Keystore
      env:
        ANDROID_KEYSTORE_PATH: ${{ github.workspace }}/android/android_keystore.jks
        ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
        ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
        ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
      run: |
        echo "${{ secrets.ANDROID_KEYSTORE_JKS }}" | base64 --decode > ${{ env.ANDROID_KEYSTORE_PATH }}
        echo "storeFile=${{ env.ANDROID_KEYSTORE_PATH }}" > android/key.properties
        echo "storePassword=${{ env.ANDROID_KEYSTORE_PASSWORD }}" >> android/key.properties
        echo "keyPassword=${{ env.ANDROID_KEY_PASSWORD }}" >> android/key.properties
        echo "keyAlias=${{ env.ANDROID_KEY_ALIAS }}" >> android/key.properties

    - name: Build Android App
      run:
        flutter build appbundle --flavor ${{ env.DEPLOY_ENV }} -t lib/main_${{ env.DEPLOY_ENV }}.dart --dart-define-from-file=.env.${{ env.DEPLOY_ENV }} --obfuscate --split-debug-info=build

    - name: Prepare for Upload
      run: |
        PACKAGE_NAME=$(grep -E "namespace\s*=\s*\"[^\"]+\"" android/app/build.gradle | sed -E 's/.*"([^"]+)".*/\1/')
        if [ "${{ env.DEPLOY_ENV }}" != "prod" ]; then
          PACKAGE_NAME="${PACKAGE_NAME}.${{ env.DEPLOY_ENV }}"
        fi
        echo "PACKAGE_NAME=$PACKAGE_NAME" >> $GITHUB_ENV
        echo "AAB_PATH=${{ github.workspace }}/build/app/outputs/bundle/${{ env.DEPLOY_ENV }}Release/app-${{ env.DEPLOY_ENV }}-release.aab" >> $GITHUB_ENV

    - name: Upload to Google Play
      uses: r0adkll/upload-google-play@v1
      with:
        # Note: First version should be updated manually.
        # See: https://github.com/r0adkll/upload-google-play
        serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}
        packageName: ${{ env.PACKAGE_NAME }}
        releaseFiles: ${{ env.AAB_PATH }}
        track: 'production'