name: Build & Upload (Android, iOS)

on:
  # push:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'prod'
        type: choice
        options:
        - dev
        - stg
        - prod

jobs:
  setup:
    uses: ./.github/workflows/01-setup.yaml

  build-android:
    needs:
      - setup
    uses: ./.github/workflows/02-build-android.yaml
    with:
      build_files_name: ${{ needs.setup.outputs.build_files_name }}
    secrets: inherit

  build-ios:
    needs:
      - setup
    uses: ./.github/workflows/03-build-ios.yaml
    with:
      build_files_name: ${{ needs.setup.outputs.build_files_name }}
    secrets: inherit

  upload-sentry:
    needs:
      - build-android
      - build-ios
    uses: ./.github/workflows/04-upload-sentry.yaml
    secrets: inherit

